// 漢字検定8級（小学3年生修了程度）練習用データ
// 各項目: kanji(漢字1字), word(出題する熟語・訓読み語), reading(そのことばの読み方), strokes(その漢字1字の総画数)
const KANJI_DATA = [
  { kanji: "医", word: "医者", reading: "いしゃ", strokes: 7 },
  { kanji: "委", word: "委員", reading: "いいん", strokes: 8 },
  { kanji: "意", word: "意味", reading: "いみ", strokes: 13 },
  { kanji: "育", word: "育てる", reading: "そだてる", strokes: 8 },
  { kanji: "員", word: "会員", reading: "かいいん", strokes: 10 },
  { kanji: "院", word: "病院", reading: "びょういん", strokes: 10 },
  { kanji: "飲", word: "飲む", reading: "のむ", strokes: 12 },
  { kanji: "運", word: "運動", reading: "うんどう", strokes: 12 },
  { kanji: "泳", word: "泳ぐ", reading: "およぐ", strokes: 8 },
  { kanji: "駅", word: "駅", reading: "えき", strokes: 14 },
  { kanji: "央", word: "中央", reading: "ちゅうおう", strokes: 5 },
  { kanji: "横", word: "横", reading: "よこ", strokes: 15 },
  { kanji: "屋", word: "部屋", reading: "へや", strokes: 9 },
  { kanji: "温", word: "気温", reading: "きおん", strokes: 12 },
  { kanji: "化", word: "変化", reading: "へんか", strokes: 4 },
  { kanji: "荷", word: "荷物", reading: "にもつ", strokes: 10 },
  { kanji: "界", word: "世界", reading: "せかい", strokes: 9 },
  { kanji: "開", word: "開ける", reading: "あける", strokes: 12 },
  { kanji: "階", word: "二階", reading: "にかい", strokes: 12 },
  { kanji: "寒", word: "寒い", reading: "さむい", strokes: 12 },
  { kanji: "感", word: "感想", reading: "かんそう", strokes: 13 },
  { kanji: "漢", word: "漢字", reading: "かんじ", strokes: 13 },
  { kanji: "館", word: "図書館", reading: "としょかん", strokes: 16 },
  { kanji: "岸", word: "海岸", reading: "かいがん", strokes: 8 },
  { kanji: "起", word: "起きる", reading: "おきる", strokes: 10 },
  { kanji: "期", word: "時期", reading: "じき", strokes: 12 },
  { kanji: "客", word: "お客", reading: "おきゃく", strokes: 9 },
  { kanji: "究", word: "研究", reading: "けんきゅう", strokes: 7 },
  { kanji: "急", word: "急ぐ", reading: "いそぐ", strokes: 9 },
  { kanji: "級", word: "学級", reading: "がっきゅう", strokes: 9 },
  { kanji: "宮", word: "宮殿", reading: "きゅうでん", strokes: 10 },
  { kanji: "球", word: "野球", reading: "やきゅう", strokes: 11 },
  { kanji: "去", word: "去年", reading: "きょねん", strokes: 5 },
  { kanji: "橋", word: "橋", reading: "はし", strokes: 16 },
  { kanji: "業", word: "授業", reading: "じゅぎょう", strokes: 13 },
  { kanji: "曲", word: "曲がる", reading: "まがる", strokes: 6 },
  { kanji: "局", word: "郵便局", reading: "ゆうびんきょく", strokes: 7 },
  { kanji: "銀", word: "銀行", reading: "ぎんこう", strokes: 14 },
  { kanji: "区", word: "区役所", reading: "くやくしょ", strokes: 4 },
  { kanji: "苦", word: "苦い", reading: "にがい", strokes: 8 },
  { kanji: "具", word: "道具", reading: "どうぐ", strokes: 8 },
  { kanji: "君", word: "君", reading: "きみ", strokes: 7 },
  { kanji: "係", word: "係", reading: "かかり", strokes: 9 },
  { kanji: "軽", word: "軽い", reading: "かるい", strokes: 12 },
  { kanji: "血", word: "血", reading: "ち", strokes: 6 },
  { kanji: "決", word: "決める", reading: "きめる", strokes: 7 },
  { kanji: "研", word: "研究", reading: "けんきゅう", strokes: 9 },
  { kanji: "県", word: "県", reading: "けん", strokes: 9 },
  { kanji: "庫", word: "車庫", reading: "しゃこ", strokes: 10 },
  { kanji: "湖", word: "湖", reading: "みずうみ", strokes: 12 },
  { kanji: "向", word: "向かう", reading: "むかう", strokes: 6 },
  { kanji: "幸", word: "幸せ", reading: "しあわせ", strokes: 8 },
  { kanji: "港", word: "港", reading: "みなと", strokes: 12 },
  { kanji: "号", word: "番号", reading: "ばんごう", strokes: 5 },
  { kanji: "根", word: "根", reading: "ね", strokes: 10 },
  { kanji: "祭", word: "祭り", reading: "まつり", strokes: 11 },
  { kanji: "皿", word: "皿", reading: "さら", strokes: 5 },
  { kanji: "仕", word: "仕事", reading: "しごと", strokes: 5 },
  { kanji: "死", word: "死ぬ", reading: "しぬ", strokes: 6 },
  { kanji: "使", word: "使う", reading: "つかう", strokes: 8 },
  { kanji: "始", word: "始まる", reading: "はじまる", strokes: 8 },
  { kanji: "指", word: "指", reading: "ゆび", strokes: 9 },
  { kanji: "歯", word: "歯", reading: "は", strokes: 12 },
  { kanji: "詩", word: "詩", reading: "し", strokes: 13 },
  { kanji: "次", word: "次", reading: "つぎ", strokes: 6 },
  { kanji: "事", word: "大事", reading: "だいじ", strokes: 8 },
  { kanji: "持", word: "持つ", reading: "もつ", strokes: 9 },
  { kanji: "式", word: "入学式", reading: "にゅうがくしき", strokes: 6 },
  { kanji: "実", word: "実", reading: "み", strokes: 8 },
  { kanji: "写", word: "写真", reading: "しゃしん", strokes: 5 },
  { kanji: "者", word: "学者", reading: "がくしゃ", strokes: 8 },
  { kanji: "主", word: "主人", reading: "しゅじん", strokes: 5 },
  { kanji: "守", word: "守る", reading: "まもる", strokes: 6 },
  { kanji: "取", word: "取る", reading: "とる", strokes: 8 },
  { kanji: "酒", word: "お酒", reading: "おさけ", strokes: 10 },
  { kanji: "受", word: "受ける", reading: "うける", strokes: 8 },
  { kanji: "州", word: "九州", reading: "きゅうしゅう", strokes: 6 },
  { kanji: "拾", word: "拾う", reading: "ひろう", strokes: 9 },
  { kanji: "終", word: "終わる", reading: "おわる", strokes: 11 },
  { kanji: "習", word: "習う", reading: "ならう", strokes: 11 },
  { kanji: "集", word: "集まる", reading: "あつまる", strokes: 12 },
  { kanji: "住", word: "住む", reading: "すむ", strokes: 7 },
  { kanji: "重", word: "重い", reading: "おもい", strokes: 9 },
  { kanji: "宿", word: "宿題", reading: "しゅくだい", strokes: 11 },
  { kanji: "所", word: "場所", reading: "ばしょ", strokes: 8 },
  { kanji: "暑", word: "暑い", reading: "あつい", strokes: 12 },
  { kanji: "助", word: "助ける", reading: "たすける", strokes: 7 },
  { kanji: "昭", word: "昭和", reading: "しょうわ", strokes: 9 },
  { kanji: "消", word: "消える", reading: "きえる", strokes: 10 },
  { kanji: "商", word: "商店", reading: "しょうてん", strokes: 11 },
  { kanji: "章", word: "文章", reading: "ぶんしょう", strokes: 11 },
  { kanji: "勝", word: "勝つ", reading: "かつ", strokes: 12 },
  { kanji: "乗", word: "乗る", reading: "のる", strokes: 9 },
  { kanji: "植", word: "植える", reading: "うえる", strokes: 12 },
  { kanji: "申", word: "申す", reading: "もうす", strokes: 5 },
  { kanji: "身", word: "中身", reading: "なかみ", strokes: 7 },
  { kanji: "神", word: "神様", reading: "かみさま", strokes: 9 },
  { kanji: "真", word: "真っ赤", reading: "まっか", strokes: 10 },
  { kanji: "深", word: "深い", reading: "ふかい", strokes: 11 },
  { kanji: "進", word: "進む", reading: "すすむ", strokes: 11 },
  { kanji: "世", word: "世界", reading: "せかい", strokes: 5 },
  { kanji: "整", word: "整える", reading: "ととのえる", strokes: 16 },
  { kanji: "昔", word: "昔", reading: "むかし", strokes: 8 },
  { kanji: "全", word: "全部", reading: "ぜんぶ", strokes: 6 },
  { kanji: "相", word: "相談", reading: "そうだん", strokes: 9 },
  { kanji: "送", word: "送る", reading: "おくる", strokes: 9 },
  { kanji: "想", word: "感想", reading: "かんそう", strokes: 13 },
  { kanji: "息", word: "息", reading: "いき", strokes: 10 },
  { kanji: "速", word: "速い", reading: "はやい", strokes: 10 },
  { kanji: "族", word: "家族", reading: "かぞく", strokes: 11 },
  { kanji: "他", word: "他", reading: "ほか", strokes: 5 },
  { kanji: "打", word: "打つ", reading: "うつ", strokes: 5 },
  { kanji: "対", word: "反対", reading: "はんたい", strokes: 7 },
  { kanji: "待", word: "待つ", reading: "まつ", strokes: 9 },
  { kanji: "代", word: "代わる", reading: "かわる", strokes: 5 },
  { kanji: "第", word: "第一", reading: "だいいち", strokes: 11 },
  { kanji: "題", word: "問題", reading: "もんだい", strokes: 18 },
  { kanji: "炭", word: "炭", reading: "すみ", strokes: 9 },
  { kanji: "短", word: "短い", reading: "みじかい", strokes: 12 },
  { kanji: "談", word: "相談", reading: "そうだん", strokes: 15 },
  { kanji: "着", word: "着く", reading: "つく", strokes: 12 },
  { kanji: "注", word: "注意", reading: "ちゅうい", strokes: 8 },
  { kanji: "柱", word: "柱", reading: "はしら", strokes: 9 },
  { kanji: "丁", word: "一丁目", reading: "いっちょうめ", strokes: 2 },
  { kanji: "帳", word: "手帳", reading: "てちょう", strokes: 11 },
  { kanji: "調", word: "調べる", reading: "しらべる", strokes: 15 },
  { kanji: "追", word: "追う", reading: "おう", strokes: 9 },
  { kanji: "定", word: "予定", reading: "よてい", strokes: 8 },
  { kanji: "庭", word: "庭", reading: "にわ", strokes: 10 },
  { kanji: "笛", word: "笛", reading: "ふえ", strokes: 11 },
  { kanji: "鉄", word: "鉄道", reading: "てつどう", strokes: 13 },
  { kanji: "転", word: "転がる", reading: "ころがる", strokes: 11 },
  { kanji: "都", word: "都会", reading: "とかい", strokes: 11 },
  { kanji: "度", word: "今度", reading: "こんど", strokes: 9 },
  { kanji: "投", word: "投げる", reading: "なげる", strokes: 7 },
  { kanji: "豆", word: "豆", reading: "まめ", strokes: 7 },
  { kanji: "島", word: "島", reading: "しま", strokes: 10 },
  { kanji: "湯", word: "お湯", reading: "おゆ", strokes: 12 },
  { kanji: "登", word: "登る", reading: "のぼる", strokes: 12 },
  { kanji: "等", word: "等しい", reading: "ひとしい", strokes: 12 },
  { kanji: "動", word: "動く", reading: "うごく", strokes: 11 },
  { kanji: "童", word: "童話", reading: "どうわ", strokes: 12 },
  { kanji: "農", word: "農家", reading: "のうか", strokes: 13 },
  { kanji: "波", word: "波", reading: "なみ", strokes: 8 },
  { kanji: "配", word: "配る", reading: "くばる", strokes: 10 },
  { kanji: "倍", word: "二倍", reading: "にばい", strokes: 10 },
  { kanji: "箱", word: "箱", reading: "はこ", strokes: 15 },
  { kanji: "畑", word: "畑", reading: "はたけ", strokes: 9 },
  { kanji: "発", word: "出発", reading: "しゅっぱつ", strokes: 9 },
  { kanji: "反", word: "反対", reading: "はんたい", strokes: 4 },
  { kanji: "板", word: "黒板", reading: "こくばん", strokes: 8 },
  { kanji: "悲", word: "悲しい", reading: "かなしい", strokes: 12 },
  { kanji: "皮", word: "皮", reading: "かわ", strokes: 5 },
  { kanji: "美", word: "美しい", reading: "うつくしい", strokes: 9 },
  { kanji: "鼻", word: "鼻", reading: "はな", strokes: 14 },
  { kanji: "筆", word: "筆箱", reading: "ふでばこ", strokes: 12 },
  { kanji: "氷", word: "氷", reading: "こおり", strokes: 5 },
  { kanji: "表", word: "表", reading: "ひょう", strokes: 8 },
  { kanji: "病", word: "病気", reading: "びょうき", strokes: 10 },
  { kanji: "秒", word: "秒", reading: "びょう", strokes: 9 },
  { kanji: "品", word: "品物", reading: "しなもの", strokes: 9 },
  { kanji: "負", word: "負ける", reading: "まける", strokes: 9 },
  { kanji: "部", word: "部屋", reading: "へや", strokes: 11 },
  { kanji: "服", word: "服", reading: "ふく", strokes: 8 },
  { kanji: "福", word: "幸福", reading: "こうふく", strokes: 13 },
  { kanji: "物", word: "物語", reading: "ものがたり", strokes: 8 },
  { kanji: "平", word: "平和", reading: "へいわ", strokes: 5 },
  { kanji: "返", word: "返す", reading: "かえす", strokes: 7 },
  { kanji: "勉", word: "勉強", reading: "べんきょう", strokes: 10 },
  { kanji: "放", word: "放す", reading: "はなす", strokes: 8 },
  { kanji: "味", word: "味", reading: "あじ", strokes: 8 },
  { kanji: "命", word: "命", reading: "いのち", strokes: 8 },
  { kanji: "面", word: "面白い", reading: "おもしろい", strokes: 9 },
  { kanji: "問", word: "問題", reading: "もんだい", strokes: 11 },
  { kanji: "役", word: "役目", reading: "やくめ", strokes: 7 },
  { kanji: "薬", word: "薬", reading: "くすり", strokes: 16 },
  { kanji: "由", word: "理由", reading: "りゆう", strokes: 5 },
  { kanji: "油", word: "油", reading: "あぶら", strokes: 8 },
  { kanji: "有", word: "有名", reading: "ゆうめい", strokes: 6 },
  { kanji: "遊", word: "遊ぶ", reading: "あそぶ", strokes: 12 },
  { kanji: "予", word: "予定", reading: "よてい", strokes: 4 },
  { kanji: "羊", word: "羊", reading: "ひつじ", strokes: 6 },
  { kanji: "洋", word: "洋服", reading: "ようふく", strokes: 9 },
  { kanji: "葉", word: "葉", reading: "は", strokes: 12 },
  { kanji: "陽", word: "太陽", reading: "たいよう", strokes: 12 },
  { kanji: "様", word: "様子", reading: "ようす", strokes: 14 },
  { kanji: "落", word: "落ちる", reading: "おちる", strokes: 12 },
  { kanji: "流", word: "流れる", reading: "ながれる", strokes: 10 },
  { kanji: "旅", word: "旅行", reading: "りょこう", strokes: 10 },
  { kanji: "両", word: "両手", reading: "りょうて", strokes: 6 },
  { kanji: "緑", word: "緑", reading: "みどり", strokes: 14 },
  { kanji: "礼", word: "お礼", reading: "おれい", strokes: 5 },
  { kanji: "列", word: "列", reading: "れつ", strokes: 6 },
  { kanji: "練", word: "練習", reading: "れんしゅう", strokes: 14 },
  { kanji: "路", word: "道路", reading: "どうろ", strokes: 13 },
  { kanji: "和", word: "平和", reading: "へいわ", strokes: 8 },
  { kanji: "悪", word: "悪い", reading: "わるい", strokes: 11 },
  { kanji: "安", word: "安い", reading: "やすい", strokes: 6 },
  { kanji: "暗", word: "暗い", reading: "くらい", strokes: 13 },
];

// 「正しい漢字えらび」用データ
// reading: 出題することば(ひらがな), correct: 正しい漢字での表記, wrong: 形が似ているが誤った漢字での表記
const CHOICE_DATA = [
  { reading: "ようじん", correct: "用心", wrong: "用思" },
  { reading: "りかしつ", correct: "理科室", wrong: "里科室" },
  { reading: "ためいけ", correct: "ため池", wrong: "ため地" },
  { reading: "まるい", correct: "丸い", wrong: "九い" },
  { reading: "すいりょく", correct: "水力", wrong: "水刀" },
  { reading: "おやどり", correct: "親鳥", wrong: "親鳴" },
  { reading: "けんきゅう", correct: "研究", wrong: "研空" },
  { reading: "しゅじん", correct: "主人", wrong: "王人" },
  { reading: "ぎんこう", correct: "銀行", wrong: "根行" },
  { reading: "かぞく", correct: "家族", wrong: "家旅" },
  { reading: "へや", correct: "部屋", wrong: "都屋" },
  { reading: "しゃしん", correct: "写真", wrong: "写直" },
  { reading: "べんきょう", correct: "勉強", wrong: "勉弱" },
  { reading: "どうろ", correct: "道路", wrong: "道略" },
  { reading: "かんそう", correct: "感想", wrong: "感相" },
  { reading: "びょういん", correct: "病院", wrong: "病完" },
  { reading: "うんどう", correct: "運動", wrong: "運働" },
  { reading: "たいよう", correct: "太陽", wrong: "太場" },
  { reading: "ようふく", correct: "洋服", wrong: "羊服" },
  { reading: "だいじ", correct: "大事", wrong: "大寺" },
  { reading: "しごと", correct: "仕事", wrong: "仕寺" },
  { reading: "はんたい", correct: "反対", wrong: "坂対" },
  { reading: "きょねん", correct: "去年", wrong: "去午" },
  { reading: "とかい", correct: "都会", wrong: "郡会" },
];

// 「対になることば」用データ
// a・b はそれぞれ { kanji, reading } の組。どちらの向きからも出題する。
const PAIR_DATA = [
  { a: { kanji: "夜", reading: "よる" }, b: { kanji: "朝", reading: "あさ" } },
  { a: { kanji: "白", reading: "しろ" }, b: { kanji: "黒", reading: "くろ" } },
  { a: { kanji: "月", reading: "つき" }, b: { kanji: "星", reading: "ほし" } },
  { a: { kanji: "肉", reading: "にく" }, b: { kanji: "魚", reading: "さかな" } },
  { a: { kanji: "雨", reading: "あめ" }, b: { kanji: "風", reading: "かぜ" } },
  { a: { kanji: "遠い", reading: "とおい" }, b: { kanji: "近い", reading: "ちかい" } },
  { a: { kanji: "広い", reading: "ひろい" }, b: { kanji: "せまい", reading: "せまい" } },
  { a: { kanji: "動く", reading: "うごく" }, b: { kanji: "止まる", reading: "とまる" } },
  { a: { kanji: "教える", reading: "おしえる" }, b: { kanji: "習う", reading: "ならう" } },
  { a: { kanji: "大きい", reading: "おおきい" }, b: { kanji: "小さい", reading: "ちいさい" } },
  { a: { kanji: "長い", reading: "ながい" }, b: { kanji: "短い", reading: "みじかい" } },
  { a: { kanji: "重い", reading: "おもい" }, b: { kanji: "軽い", reading: "かるい" } },
  { a: { kanji: "明るい", reading: "あかるい" }, b: { kanji: "暗い", reading: "くらい" } },
  { a: { kanji: "強い", reading: "つよい" }, b: { kanji: "弱い", reading: "よわい" } },
  { a: { kanji: "上", reading: "うえ" }, b: { kanji: "下", reading: "した" } },
  { a: { kanji: "前", reading: "まえ" }, b: { kanji: "後ろ", reading: "うしろ" } },
  { a: { kanji: "兄", reading: "あに" }, b: { kanji: "妹", reading: "いもうと" } },
  { a: { kanji: "父", reading: "ちち" }, b: { kanji: "母", reading: "はは" } },
  { a: { kanji: "買う", reading: "かう" }, b: { kanji: "売る", reading: "うる" } },
  { a: { kanji: "始まる", reading: "はじまる" }, b: { kanji: "終わる", reading: "おわる" } },
];

/* =========================================================
   9級（小学2年生修了程度）データ
   文部科学省「学年別漢字配当表」の第2学年配当漢字（160字）に
   もとづく。各項目の形式は KANJI_DATA と同じ。
   ========================================================= */
const GRADE2_DATA = [
  { kanji: "引", word: "引く", reading: "ひく", strokes: 4 },
  { kanji: "羽", word: "羽", reading: "はね", strokes: 6 },
  { kanji: "雲", word: "雲", reading: "くも", strokes: 12 },
  { kanji: "園", word: "公園", reading: "こうえん", strokes: 13 },
  { kanji: "遠", word: "遠い", reading: "とおい", strokes: 13 },
  { kanji: "何", word: "何", reading: "なに", strokes: 7 },
  { kanji: "科", word: "教科", reading: "きょうか", strokes: 9 },
  { kanji: "夏", word: "夏", reading: "なつ", strokes: 10 },
  { kanji: "家", word: "家", reading: "いえ", strokes: 10 },
  { kanji: "歌", word: "歌", reading: "うた", strokes: 14 },
  { kanji: "画", word: "画用紙", reading: "がようし", strokes: 8 },
  { kanji: "回", word: "回る", reading: "まわる", strokes: 6 },
  { kanji: "会", word: "会う", reading: "あう", strokes: 6 },
  { kanji: "海", word: "海", reading: "うみ", strokes: 9 },
  { kanji: "絵", word: "絵", reading: "え", strokes: 12 },
  { kanji: "外", word: "外", reading: "そと", strokes: 5 },
  { kanji: "角", word: "角", reading: "かど", strokes: 7 },
  { kanji: "楽", word: "楽しい", reading: "たのしい", strokes: 13 },
  { kanji: "活", word: "生活", reading: "せいかつ", strokes: 9 },
  { kanji: "間", word: "間", reading: "あいだ", strokes: 12 },
  { kanji: "丸", word: "丸い", reading: "まるい", strokes: 3 },
  { kanji: "岩", word: "岩", reading: "いわ", strokes: 8 },
  { kanji: "顔", word: "顔", reading: "かお", strokes: 18 },
  { kanji: "汽", word: "汽車", reading: "きしゃ", strokes: 7 },
  { kanji: "記", word: "日記", reading: "にっき", strokes: 10 },
  { kanji: "帰", word: "帰る", reading: "かえる", strokes: 10 },
  { kanji: "弓", word: "弓", reading: "ゆみ", strokes: 3 },
  { kanji: "牛", word: "牛", reading: "うし", strokes: 4 },
  { kanji: "魚", word: "魚", reading: "さかな", strokes: 11 },
  { kanji: "京", word: "東京", reading: "とうきょう", strokes: 8 },
  { kanji: "強", word: "強い", reading: "つよい", strokes: 11 },
  { kanji: "教", word: "教える", reading: "おしえる", strokes: 11 },
  { kanji: "近", word: "近い", reading: "ちかい", strokes: 7 },
  { kanji: "兄", word: "兄", reading: "あに", strokes: 5 },
  { kanji: "形", word: "形", reading: "かたち", strokes: 7 },
  { kanji: "計", word: "時計", reading: "とけい", strokes: 9 },
  { kanji: "元", word: "元気", reading: "げんき", strokes: 4 },
  { kanji: "言", word: "言う", reading: "いう", strokes: 7 },
  { kanji: "原", word: "野原", reading: "のはら", strokes: 10 },
  { kanji: "戸", word: "戸", reading: "と", strokes: 4 },
  { kanji: "古", word: "古い", reading: "ふるい", strokes: 5 },
  { kanji: "午", word: "午後", reading: "ごご", strokes: 4 },
  { kanji: "後", word: "後ろ", reading: "うしろ", strokes: 9 },
  { kanji: "語", word: "国語", reading: "こくご", strokes: 14 },
  { kanji: "工", word: "工作", reading: "こうさく", strokes: 3 },
  { kanji: "公", word: "公園", reading: "こうえん", strokes: 4 },
  { kanji: "広", word: "広い", reading: "ひろい", strokes: 5 },
  { kanji: "交", word: "交番", reading: "こうばん", strokes: 6 },
  { kanji: "光", word: "光", reading: "ひかり", strokes: 6 },
  { kanji: "考", word: "考える", reading: "かんがえる", strokes: 6 },
  { kanji: "行", word: "行く", reading: "いく", strokes: 6 },
  { kanji: "高", word: "高い", reading: "たかい", strokes: 10 },
  { kanji: "黄", word: "黄色", reading: "きいろ", strokes: 11 },
  { kanji: "合", word: "合う", reading: "あう", strokes: 6 },
  { kanji: "谷", word: "谷", reading: "たに", strokes: 7 },
  { kanji: "国", word: "国", reading: "くに", strokes: 8 },
  { kanji: "黒", word: "黒い", reading: "くろい", strokes: 11 },
  { kanji: "今", word: "今", reading: "いま", strokes: 4 },
  { kanji: "才", word: "三才", reading: "さんさい", strokes: 3 },
  { kanji: "細", word: "細い", reading: "ほそい", strokes: 11 },
  { kanji: "作", word: "作る", reading: "つくる", strokes: 7 },
  { kanji: "算", word: "計算", reading: "けいさん", strokes: 14 },
  { kanji: "止", word: "止まる", reading: "とまる", strokes: 4 },
  { kanji: "市", word: "市", reading: "し", strokes: 5 },
  { kanji: "矢", word: "矢", reading: "や", strokes: 5 },
  { kanji: "姉", word: "姉", reading: "あね", strokes: 8 },
  { kanji: "思", word: "思う", reading: "おもう", strokes: 9 },
  { kanji: "紙", word: "紙", reading: "かみ", strokes: 10 },
  { kanji: "寺", word: "お寺", reading: "おてら", strokes: 6 },
  { kanji: "自", word: "自分", reading: "じぶん", strokes: 6 },
  { kanji: "時", word: "時", reading: "とき", strokes: 10 },
  { kanji: "室", word: "教室", reading: "きょうしつ", strokes: 9 },
  { kanji: "社", word: "会社", reading: "かいしゃ", strokes: 7 },
  { kanji: "弱", word: "弱い", reading: "よわい", strokes: 10 },
  { kanji: "首", word: "首", reading: "くび", strokes: 9 },
  { kanji: "秋", word: "秋", reading: "あき", strokes: 9 },
  { kanji: "週", word: "今週", reading: "こんしゅう", strokes: 11 },
  { kanji: "春", word: "春", reading: "はる", strokes: 9 },
  { kanji: "書", word: "書く", reading: "かく", strokes: 10 },
  { kanji: "少", word: "少ない", reading: "すくない", strokes: 4 },
  { kanji: "場", word: "会場", reading: "かいじょう", strokes: 12 },
  { kanji: "色", word: "色", reading: "いろ", strokes: 6 },
  { kanji: "食", word: "食べる", reading: "たべる", strokes: 9 },
  { kanji: "心", word: "心", reading: "こころ", strokes: 4 },
  { kanji: "新", word: "新しい", reading: "あたらしい", strokes: 13 },
  { kanji: "親", word: "親", reading: "おや", strokes: 16 },
  { kanji: "図", word: "図工", reading: "ずこう", strokes: 7 },
  { kanji: "数", word: "数", reading: "かず", strokes: 13 },
  { kanji: "西", word: "西", reading: "にし", strokes: 6 },
  { kanji: "声", word: "声", reading: "こえ", strokes: 7 },
  { kanji: "星", word: "星", reading: "ほし", strokes: 9 },
  { kanji: "晴", word: "晴れる", reading: "はれる", strokes: 12 },
  { kanji: "切", word: "切る", reading: "きる", strokes: 4 },
  { kanji: "雪", word: "雪", reading: "ゆき", strokes: 11 },
  { kanji: "船", word: "船", reading: "ふね", strokes: 11 },
  { kanji: "線", word: "線", reading: "せん", strokes: 15 },
  { kanji: "前", word: "前", reading: "まえ", strokes: 9 },
  { kanji: "組", word: "組", reading: "くみ", strokes: 11 },
  { kanji: "走", word: "走る", reading: "はしる", strokes: 7 },
  { kanji: "多", word: "多い", reading: "おおい", strokes: 6 },
  { kanji: "太", word: "太い", reading: "ふとい", strokes: 4 },
  { kanji: "体", word: "体", reading: "からだ", strokes: 7 },
  { kanji: "台", word: "台所", reading: "だいどころ", strokes: 5 },
  { kanji: "地", word: "地面", reading: "じめん", strokes: 6 },
  { kanji: "池", word: "池", reading: "いけ", strokes: 6 },
  { kanji: "知", word: "知る", reading: "しる", strokes: 8 },
  { kanji: "茶", word: "お茶", reading: "おちゃ", strokes: 9 },
  { kanji: "昼", word: "昼", reading: "ひる", strokes: 9 },
  { kanji: "長", word: "長い", reading: "ながい", strokes: 8 },
  { kanji: "鳥", word: "鳥", reading: "とり", strokes: 11 },
  { kanji: "朝", word: "朝", reading: "あさ", strokes: 12 },
  { kanji: "直", word: "直す", reading: "なおす", strokes: 8 },
  { kanji: "通", word: "通る", reading: "とおる", strokes: 10 },
  { kanji: "弟", word: "弟", reading: "おとうと", strokes: 7 },
  { kanji: "店", word: "店", reading: "みせ", strokes: 8 },
  { kanji: "点", word: "点", reading: "てん", strokes: 9 },
  { kanji: "電", word: "電気", reading: "でんき", strokes: 13 },
  { kanji: "刀", word: "刀", reading: "かたな", strokes: 2 },
  { kanji: "冬", word: "冬", reading: "ふゆ", strokes: 5 },
  { kanji: "当", word: "当たる", reading: "あたる", strokes: 6 },
  { kanji: "東", word: "東", reading: "ひがし", strokes: 8 },
  { kanji: "答", word: "答える", reading: "こたえる", strokes: 12 },
  { kanji: "頭", word: "頭", reading: "あたま", strokes: 16 },
  { kanji: "同", word: "同じ", reading: "おなじ", strokes: 6 },
  { kanji: "道", word: "道", reading: "みち", strokes: 12 },
  { kanji: "読", word: "読む", reading: "よむ", strokes: 14 },
  { kanji: "内", word: "内", reading: "うち", strokes: 4 },
  { kanji: "南", word: "南", reading: "みなみ", strokes: 9 },
  { kanji: "肉", word: "肉", reading: "にく", strokes: 6 },
  { kanji: "馬", word: "馬", reading: "うま", strokes: 10 },
  { kanji: "売", word: "売る", reading: "うる", strokes: 7 },
  { kanji: "買", word: "買う", reading: "かう", strokes: 12 },
  { kanji: "麦", word: "麦", reading: "むぎ", strokes: 7 },
  { kanji: "半", word: "半分", reading: "はんぶん", strokes: 5 },
  { kanji: "番", word: "一番", reading: "いちばん", strokes: 12 },
  { kanji: "父", word: "父", reading: "ちち", strokes: 4 },
  { kanji: "風", word: "風", reading: "かぜ", strokes: 9 },
  { kanji: "分", word: "分ける", reading: "わける", strokes: 4 },
  { kanji: "聞", word: "聞く", reading: "きく", strokes: 14 },
  { kanji: "米", word: "米", reading: "こめ", strokes: 6 },
  { kanji: "歩", word: "歩く", reading: "あるく", strokes: 8 },
  { kanji: "母", word: "母", reading: "はは", strokes: 5 },
  { kanji: "方", word: "方", reading: "ほう", strokes: 4 },
  { kanji: "北", word: "北", reading: "きた", strokes: 5 },
  { kanji: "毎", word: "毎日", reading: "まいにち", strokes: 6 },
  { kanji: "妹", word: "妹", reading: "いもうと", strokes: 8 },
  { kanji: "万", word: "一万", reading: "いちまん", strokes: 3 },
  { kanji: "明", word: "明るい", reading: "あかるい", strokes: 8 },
  { kanji: "鳴", word: "鳴く", reading: "なく", strokes: 14 },
  { kanji: "毛", word: "毛", reading: "け", strokes: 4 },
  { kanji: "門", word: "門", reading: "もん", strokes: 8 },
  { kanji: "夜", word: "夜", reading: "よる", strokes: 8 },
  { kanji: "野", word: "野菜", reading: "やさい", strokes: 11 },
  { kanji: "友", word: "友だち", reading: "ともだち", strokes: 4 },
  { kanji: "用", word: "用いる", reading: "もちいる", strokes: 5 },
  { kanji: "曜", word: "火曜日", reading: "かようび", strokes: 18 },
  { kanji: "来", word: "来る", reading: "くる", strokes: 7 },
  { kanji: "里", word: "里", reading: "さと", strokes: 7 },
  { kanji: "理", word: "理科", reading: "りか", strokes: 11 },
  { kanji: "話", word: "話す", reading: "はなす", strokes: 13 },
];

// 9級用「正しい漢字えらび」データ（形が似ている漢字の二択）
const GRADE2_CHOICE_DATA = [
  { reading: "きしゃ", correct: "汽車", wrong: "気車" },
  { reading: "おしえる", correct: "教える", wrong: "数える" },
  { reading: "ふとい", correct: "太い", wrong: "大い" },
  { reading: "こうばん", correct: "交番", wrong: "校番" },
  { reading: "ずこう", correct: "図工", wrong: "因工" },
  { reading: "すくない", correct: "少ない", wrong: "小ない" },
  { reading: "くび", correct: "首", wrong: "道" },
  { reading: "よわい", correct: "弱い", wrong: "弓い" },
  { reading: "くみ", correct: "組", wrong: "細" },
  { reading: "とけい", correct: "時計", wrong: "持計" },
  { reading: "かいしゃ", correct: "会社", wrong: "合社" },
  { reading: "こくご", correct: "国語", wrong: "国話" },
  { reading: "せいかつ", correct: "生活", wrong: "生話" },
  { reading: "けいさん", correct: "計算", wrong: "討算" },
  { reading: "はんぶん", correct: "半分", wrong: "羊分" },
  { reading: "いちまん", correct: "一万", wrong: "一方" },
];

// 9級用「対になることば」データ
const GRADE2_PAIR_DATA = [
  { a: { kanji: "兄", reading: "あに" }, b: { kanji: "弟", reading: "おとうと" } },
  { a: { kanji: "姉", reading: "あね" }, b: { kanji: "妹", reading: "いもうと" } },
  { a: { kanji: "父", reading: "ちち" }, b: { kanji: "母", reading: "はは" } },
  { a: { kanji: "朝", reading: "あさ" }, b: { kanji: "夜", reading: "よる" } },
  { a: { kanji: "太い", reading: "ふとい" }, b: { kanji: "細い", reading: "ほそい" } },
  { a: { kanji: "強い", reading: "つよい" }, b: { kanji: "弱い", reading: "よわい" } },
  { a: { kanji: "多い", reading: "おおい" }, b: { kanji: "少ない", reading: "すくない" } },
  { a: { kanji: "広い", reading: "ひろい" }, b: { kanji: "せまい", reading: "せまい" } },
  { a: { kanji: "新しい", reading: "あたらしい" }, b: { kanji: "古い", reading: "ふるい" } },
  { a: { kanji: "東", reading: "ひがし" }, b: { kanji: "西", reading: "にし" } },
  { a: { kanji: "南", reading: "みなみ" }, b: { kanji: "北", reading: "きた" } },
  { a: { kanji: "買う", reading: "かう" }, b: { kanji: "売る", reading: "うる" } },
  { a: { kanji: "行く", reading: "いく" }, b: { kanji: "来る", reading: "くる" } },
  { a: { kanji: "遠い", reading: "とおい" }, b: { kanji: "近い", reading: "ちかい" } },
  { a: { kanji: "夏", reading: "なつ" }, b: { kanji: "冬", reading: "ふゆ" } },
  { a: { kanji: "春", reading: "はる" }, b: { kanji: "秋", reading: "あき" } },
  { a: { kanji: "前", reading: "まえ" }, b: { kanji: "後ろ", reading: "うしろ" } },
];

/* =========================================================
   部首なかまさがし用データ（9級・8級 共通）
   同じ部首を持つ漢字のグループ。どの学年の漢字表にもとづく
   一般に知られた部首分類で、レベルを問わず出題する。
   ========================================================= */
const RADICAL_GROUPS = [
  {
    radical: "氵（さんずい）",
    kanji: ["海", "活", "汽", "池", "泳", "港", "湖", "油", "流", "消", "深", "決", "注", "洋"],
  },
  { radical: "木（きへん）", kanji: ["板", "横", "植", "根", "様", "柱", "橋"] },
  { radical: "扌（てへん）", kanji: ["持", "打", "指", "拾", "投"] },
  { radical: "言（ごんべん）", kanji: ["語", "話", "記", "計", "詩", "談", "調"] },
  { radical: "イ（にんべん）", kanji: ["体", "作", "何", "係", "住", "使", "倍", "他", "代"] },
  { radical: "艹（くさかんむり）", kanji: ["茶", "苦", "葉", "薬", "落"] },
  { radical: "日（ひへん）", kanji: ["時", "晴", "暑", "暗", "昔", "曜", "昭", "昼"] },
  { radical: "心（こころ）", kanji: ["感", "想", "息", "悲", "思", "急"] },
  { radical: "女（おんなへん）", kanji: ["姉", "始", "妹"] },
];
