// 漢字検定8級（小学3年生修了程度）練習用データ
// 各項目: kanji(漢字1字), word(出題する熟語・訓読み語), reading(そのことばの読み方), strokes(その漢字1字の総画数)
const KANJI_DATA = [
  { kanji: "医", word: "医者", reading: "いしゃ", strokes: 7 },
  { kanji: "委", word: "委員", reading: "いいん", strokes: 8 },
  { kanji: "意", word: "意味", reading: "いみ", strokes: 13 },
  { kanji: "育", word: "育てる", reading: "そだてる", strokes: 8 },
  { kanji: "員", word: "会員", reading: "かいいん", strokes: 10 },
  { kanji: "院", word: "病院", reading: "びょういん", strokes: 10 },
  { kanji: "飲", word: "飲む", reading: "のむ", strokes: 12 },
  { kanji: "運", word: "運動", reading: "うんどう", strokes: 12 },
  { kanji: "泳", word: "泳ぐ", reading: "およぐ", strokes: 8 },
  { kanji: "駅", word: "駅", reading: "えき", strokes: 14 },
  { kanji: "央", word: "中央", reading: "ちゅうおう", strokes: 5 },
  { kanji: "横", word: "横", reading: "よこ", strokes: 15 },
  { kanji: "屋", word: "部屋", reading: "へや", strokes: 9 },
  { kanji: "温", word: "気温", reading: "きおん", strokes: 12 },
  { kanji: "化", word: "変化", reading: "へんか", strokes: 4 },
  { kanji: "荷", word: "荷物", reading: "にもつ", strokes: 10 },
  { kanji: "界", word: "世界", reading: "せかい", strokes: 9 },
  { kanji: "開", word: "開ける", reading: "あける", strokes: 12 },
  { kanji: "階", word: "二階", reading: "にかい", strokes: 12 },
  { kanji: "寒", word: "寒い", reading: "さむい", strokes: 12 },
  { kanji: "感", word: "感想", reading: "かんそう", strokes: 13 },
  { kanji: "漢", word: "漢字", reading: "かんじ", strokes: 13 },
  { kanji: "館", word: "図書館", reading: "としょかん", strokes: 16 },
  { kanji: "岸", word: "海岸", reading: "かいがん", strokes: 8 },
  { kanji: "起", word: "起きる", reading: "おきる", strokes: 10 },
  { kanji: "期", word: "時期", reading: "じき", strokes: 12 },
  { kanji: "客", word: "お客", reading: "おきゃく", strokes: 9 },
  { kanji: "究", word: "研究", reading: "けんきゅう", strokes: 7 },
  { kanji: "急", word: "急ぐ", reading: "いそぐ", strokes: 9 },
  { kanji: "級", word: "学級", reading: "がっきゅう", strokes: 9 },
  { kanji: "宮", word: "宮殿", reading: "きゅうでん", strokes: 10 },
  { kanji: "球", word: "野球", reading: "やきゅう", strokes: 11 },
  { kanji: "去", word: "去年", reading: "きょねん", strokes: 5 },
  { kanji: "橋", word: "橋", reading: "はし", strokes: 16 },
  { kanji: "業", word: "授業", reading: "じゅぎょう", strokes: 13 },
  { kanji: "曲", word: "曲がる", reading: "まがる", strokes: 6 },
  { kanji: "局", word: "郵便局", reading: "ゆうびんきょく", strokes: 7 },
  { kanji: "銀", word: "銀行", reading: "ぎんこう", strokes: 14 },
  { kanji: "区", word: "区役所", reading: "くやくしょ", strokes: 4 },
  { kanji: "苦", word: "苦い", reading: "にがい", strokes: 8 },
  { kanji: "具", word: "道具", reading: "どうぐ", strokes: 8 },
  { kanji: "君", word: "君", reading: "きみ", strokes: 7 },
  { kanji: "係", word: "係", reading: "かかり", strokes: 9 },
  { kanji: "軽", word: "軽い", reading: "かるい", strokes: 12 },
  { kanji: "血", word: "血", reading: "ち", strokes: 6 },
  { kanji: "決", word: "決める", reading: "きめる", strokes: 7 },
  { kanji: "研", word: "研究", reading: "けんきゅう", strokes: 9 },
  { kanji: "県", word: "県", reading: "けん", strokes: 9 },
  { kanji: "庫", word: "車庫", reading: "しゃこ", strokes: 10 },
  { kanji: "湖", word: "湖", reading: "みずうみ", strokes: 12 },
  { kanji: "向", word: "向かう", reading: "むかう", strokes: 6 },
  { kanji: "幸", word: "幸せ", reading: "しあわせ", strokes: 8 },
  { kanji: "港", word: "港", reading: "みなと", strokes: 12 },
  { kanji: "号", word: "番号", reading: "ばんごう", strokes: 5 },
  { kanji: "根", word: "根", reading: "ね", strokes: 10 },
  { kanji: "祭", word: "祭り", reading: "まつり", strokes: 11 },
  { kanji: "皿", word: "皿", reading: "さら", strokes: 5 },
  { kanji: "仕", word: "仕事", reading: "しごと", strokes: 5 },
  { kanji: "死", word: "死ぬ", reading: "しぬ", strokes: 6 },
  { kanji: "使", word: "使う", reading: "つかう", strokes: 8 },
  { kanji: "始", word: "始まる", reading: "はじまる", strokes: 8 },
  { kanji: "指", word: "指", reading: "ゆび", strokes: 9 },
  { kanji: "歯", word: "歯", reading: "は", strokes: 12 },
  { kanji: "詩", word: "詩", reading: "し", strokes: 13 },
  { kanji: "次", word: "次", reading: "つぎ", strokes: 6 },
  { kanji: "事", word: "大事", reading: "だいじ", strokes: 8 },
  { kanji: "持", word: "持つ", reading: "もつ", strokes: 9 },
  { kanji: "式", word: "入学式", reading: "にゅうがくしき", strokes: 6 },
  { kanji: "実", word: "実", reading: "み", strokes: 8 },
  { kanji: "写", word: "写真", reading: "しゃしん", strokes: 5 },
  { kanji: "者", word: "学者", reading: "がくしゃ", strokes: 8 },
  { kanji: "主", word: "主人", reading: "しゅじん", strokes: 5 },
  { kanji: "守", word: "守る", reading: "まもる", strokes: 6 },
  { kanji: "取", word: "取る", reading: "とる", strokes: 8 },
  { kanji: "酒", word: "お酒", reading: "おさけ", strokes: 10 },
  { kanji: "受", word: "受ける", reading: "うける", strokes: 8 },
  { kanji: "州", word: "九州", reading: "きゅうしゅう", strokes: 6 },
  { kanji: "拾", word: "拾う", reading: "ひろう", strokes: 9 },
  { kanji: "終", word: "終わる", reading: "おわる", strokes: 11 },
  { kanji: "習", word: "習う", reading: "ならう", strokes: 11 },
  { kanji: "集", word: "集まる", reading: "あつまる", strokes: 12 },
  { kanji: "住", word: "住む", reading: "すむ", strokes: 7 },
  { kanji: "重", word: "重い", reading: "おもい", strokes: 9 },
  { kanji: "宿", word: "宿題", reading: "しゅくだい", strokes: 11 },
  { kanji: "所", word: "場所", reading: "ばしょ", strokes: 8 },
  { kanji: "暑", word: "暑い", reading: "あつい", strokes: 12 },
  { kanji: "助", word: "助ける", reading: "たすける", strokes: 7 },
  { kanji: "昭", word: "昭和", reading: "しょうわ", strokes: 9 },
  { kanji: "消", word: "消える", reading: "きえる", strokes: 10 },
  { kanji: "商", word: "商店", reading: "しょうてん", strokes: 11 },
  { kanji: "章", word: "文章", reading: "ぶんしょう", strokes: 11 },
  { kanji: "勝", word: "勝つ", reading: "かつ", strokes: 12 },
  { kanji: "乗", word: "乗る", reading: "のる", strokes: 9 },
  { kanji: "植", word: "植える", reading: "うえる", strokes: 12 },
  { kanji: "申", word: "申す", reading: "もうす", strokes: 5 },
  { kanji: "身", word: "中身", reading: "なかみ", strokes: 7 },
  { kanji: "神", word: "神様", reading: "かみさま", strokes: 9 },
  { kanji: "真", word: "真っ赤", reading: "まっか", strokes: 10 },
  { kanji: "深", word: "深い", reading: "ふかい", strokes: 11 },
  { kanji: "進", word: "進む", reading: "すすむ", strokes: 11 },
  { kanji: "世", word: "世界", reading: "せかい", strokes: 5 },
  { kanji: "整", word: "整える", reading: "ととのえる", strokes: 16 },
  { kanji: "昔", word: "昔", reading: "むかし", strokes: 8 },
  { kanji: "全", word: "全部", reading: "ぜんぶ", strokes: 6 },
  { kanji: "相", word: "相談", reading: "そうだん", strokes: 9 },
  { kanji: "送", word: "送る", reading: "おくる", strokes: 9 },
  { kanji: "想", word: "感想", reading: "かんそう", strokes: 13 },
  { kanji: "息", word: "息", reading: "いき", strokes: 10 },
  { kanji: "速", word: "速い", reading: "はやい", strokes: 10 },
  { kanji: "族", word: "家族", reading: "かぞく", strokes: 11 },
  { kanji: "他", word: "他", reading: "ほか", strokes: 5 },
  { kanji: "打", word: "打つ", reading: "うつ", strokes: 5 },
  { kanji: "対", word: "反対", reading: "はんたい", strokes: 7 },
  { kanji: "待", word: "待つ", reading: "まつ", strokes: 9 },
  { kanji: "代", word: "代わる", reading: "かわる", strokes: 5 },
  { kanji: "第", word: "第一", reading: "だいいち", strokes: 11 },
  { kanji: "題", word: "問題", reading: "もんだい", strokes: 18 },
  { kanji: "炭", word: "炭", reading: "すみ", strokes: 9 },
  { kanji: "短", word: "短い", reading: "みじかい", strokes: 12 },
  { kanji: "談", word: "相談", reading: "そうだん", strokes: 15 },
  { kanji: "着", word: "着く", reading: "つく", strokes: 12 },
  { kanji: "注", word: "注意", reading: "ちゅうい", strokes: 8 },
  { kanji: "柱", word: "柱", reading: "はしら", strokes: 9 },
  { kanji: "丁", word: "一丁目", reading: "いっちょうめ", strokes: 2 },
  { kanji: "帳", word: "手帳", reading: "てちょう", strokes: 11 },
  { kanji: "調", word: "調べる", reading: "しらべる", strokes: 15 },
  { kanji: "追", word: "追う", reading: "おう", strokes: 9 },
  { kanji: "定", word: "予定", reading: "よてい", strokes: 8 },
  { kanji: "庭", word: "庭", reading: "にわ", strokes: 10 },
  { kanji: "笛", word: "笛", reading: "ふえ", strokes: 11 },
  { kanji: "鉄", word: "鉄道", reading: "てつどう", strokes: 13 },
  { kanji: "転", word: "転がる", reading: "ころがる", strokes: 11 },
  { kanji: "都", word: "都会", reading: "とかい", strokes: 11 },
  { kanji: "度", word: "今度", reading: "こんど", strokes: 9 },
  { kanji: "投", word: "投げる", reading: "なげる", strokes: 7 },
  { kanji: "豆", word: "豆", reading: "まめ", strokes: 7 },
  { kanji: "島", word: "島", reading: "しま", strokes: 10 },
  { kanji: "湯", word: "お湯", reading: "おゆ", strokes: 12 },
  { kanji: "登", word: "登る", reading: "のぼる", strokes: 12 },
  { kanji: "等", word: "等しい", reading: "ひとしい", strokes: 12 },
  { kanji: "動", word: "動く", reading: "うごく", strokes: 11 },
  { kanji: "童", word: "童話", reading: "どうわ", strokes: 12 },
  { kanji: "農", word: "農家", reading: "のうか", strokes: 13 },
  { kanji: "波", word: "波", reading: "なみ", strokes: 8 },
  { kanji: "配", word: "配る", reading: "くばる", strokes: 10 },
  { kanji: "倍", word: "二倍", reading: "にばい", strokes: 10 },
  { kanji: "箱", word: "箱", reading: "はこ", strokes: 15 },
  { kanji: "畑", word: "畑", reading: "はたけ", strokes: 9 },
  { kanji: "発", word: "出発", reading: "しゅっぱつ", strokes: 9 },
  { kanji: "反", word: "反対", reading: "はんたい", strokes: 4 },
  { kanji: "板", word: "黒板", reading: "こくばん", strokes: 8 },
  { kanji: "悲", word: "悲しい", reading: "かなしい", strokes: 12 },
  { kanji: "皮", word: "皮", reading: "かわ", strokes: 5 },
  { kanji: "美", word: "美しい", reading: "うつくしい", strokes: 9 },
  { kanji: "鼻", word: "鼻", reading: "はな", strokes: 14 },
  { kanji: "筆", word: "筆箱", reading: "ふでばこ", strokes: 12 },
  { kanji: "氷", word: "氷", reading: "こおり", strokes: 5 },
  { kanji: "表", word: "表", reading: "ひょう", strokes: 8 },
  { kanji: "病", word: "病気", reading: "びょうき", strokes: 10 },
  { kanji: "秒", word: "秒", reading: "びょう", strokes: 9 },
  { kanji: "品", word: "品物", reading: "しなもの", strokes: 9 },
  { kanji: "負", word: "負ける", reading: "まける", strokes: 9 },
  { kanji: "部", word: "部屋", reading: "へや", strokes: 11 },
  { kanji: "服", word: "服", reading: "ふく", strokes: 8 },
  { kanji: "福", word: "幸福", reading: "こうふく", strokes: 13 },
  { kanji: "物", word: "物語", reading: "ものがたり", strokes: 8 },
  { kanji: "平", word: "平和", reading: "へいわ", strokes: 5 },
  { kanji: "返", word: "返す", reading: "かえす", strokes: 7 },
  { kanji: "勉", word: "勉強", reading: "べんきょう", strokes: 10 },
  { kanji: "放", word: "放す", reading: "はなす", strokes: 8 },
  { kanji: "味", word: "味", reading: "あじ", strokes: 8 },
  { kanji: "命", word: "命", reading: "いのち", strokes: 8 },
  { kanji: "面", word: "面白い", reading: "おもしろい", strokes: 9 },
  { kanji: "問", word: "問題", reading: "もんだい", strokes: 11 },
  { kanji: "役", word: "役目", reading: "やくめ", strokes: 7 },
  { kanji: "薬", word: "薬", reading: "くすり", strokes: 16 },
  { kanji: "由", word: "理由", reading: "りゆう", strokes: 5 },
  { kanji: "油", word: "油", reading: "あぶら", strokes: 8 },
  { kanji: "有", word: "有名", reading: "ゆうめい", strokes: 6 },
  { kanji: "遊", word: "遊ぶ", reading: "あそぶ", strokes: 12 },
  { kanji: "予", word: "予定", reading: "よてい", strokes: 4 },
  { kanji: "羊", word: "羊", reading: "ひつじ", strokes: 6 },
  { kanji: "洋", word: "洋服", reading: "ようふく", strokes: 9 },
  { kanji: "葉", word: "葉", reading: "は", strokes: 12 },
  { kanji: "陽", word: "太陽", reading: "たいよう", strokes: 12 },
  { kanji: "様", word: "様子", reading: "ようす", strokes: 14 },
  { kanji: "落", word: "落ちる", reading: "おちる", strokes: 12 },
  { kanji: "流", word: "流れる", reading: "ながれる", strokes: 10 },
  { kanji: "旅", word: "旅行", reading: "りょこう", strokes: 10 },
  { kanji: "両", word: "両手", reading: "りょうて", strokes: 6 },
  { kanji: "緑", word: "緑", reading: "みどり", strokes: 14 },
  { kanji: "礼", word: "お礼", reading: "おれい", strokes: 5 },
  { kanji: "列", word: "列", reading: "れつ", strokes: 6 },
  { kanji: "練", word: "練習", reading: "れんしゅう", strokes: 14 },
  { kanji: "路", word: "道路", reading: "どうろ", strokes: 13 },
  { kanji: "和", word: "平和", reading: "へいわ", strokes: 8 },
  { kanji: "悪", word: "悪い", reading: "わるい", strokes: 11 },
  { kanji: "安", word: "安い", reading: "やすい", strokes: 6 },
  { kanji: "暗", word: "暗い", reading: "くらい", strokes: 13 },
];

// 「正しい漢字えらび」用データ
// reading: 出題することば(ひらがな), correct: 正しい漢字での表記, wrong: 形が似ているが誤った漢字での表記
const CHOICE_DATA = [
  { reading: "ようじん", correct: "用心", wrong: "用思" },
  { reading: "りかしつ", correct: "理科室", wrong: "里科室" },
  { reading: "ためいけ", correct: "ため池", wrong: "ため地" },
  { reading: "まるい", correct: "丸い", wrong: "九い" },
  { reading: "すいりょく", correct: "水力", wrong: "水刀" },
  { reading: "おやどり", correct: "親鳥", wrong: "親鳴" },
  { reading: "けんきゅう", correct: "研究", wrong: "研空" },
  { reading: "しゅじん", correct: "主人", wrong: "王人" },
  { reading: "ぎんこう", correct: "銀行", wrong: "根行" },
  { reading: "かぞく", correct: "家族", wrong: "家旅" },
  { reading: "へや", correct: "部屋", wrong: "都屋" },
  { reading: "しゃしん", correct: "写真", wrong: "写直" },
  { reading: "べんきょう", correct: "勉強", wrong: "勉弱" },
  { reading: "どうろ", correct: "道路", wrong: "道略" },
  { reading: "かんそう", correct: "感想", wrong: "感相" },
  { reading: "びょういん", correct: "病院", wrong: "病完" },
  { reading: "うんどう", correct: "運動", wrong: "運働" },
  { reading: "たいよう", correct: "太陽", wrong: "太場" },
  { reading: "ようふく", correct: "洋服", wrong: "羊服" },
  { reading: "だいじ", correct: "大事", wrong: "大寺" },
  { reading: "しごと", correct: "仕事", wrong: "仕寺" },
  { reading: "はんたい", correct: "反対", wrong: "坂対" },
  { reading: "きょねん", correct: "去年", wrong: "去午" },
  { reading: "とかい", correct: "都会", wrong: "郡会" },
];

// 「対になることば」用データ
// a・b はそれぞれ { kanji, reading } の組。どちらの向きからも出題する。
const PAIR_DATA = [
  { a: { kanji: "夜", reading: "よる" }, b: { kanji: "朝", reading: "あさ" } },
  { a: { kanji: "白", reading: "しろ" }, b: { kanji: "黒", reading: "くろ" } },
  { a: { kanji: "月", reading: "つき" }, b: { kanji: "星", reading: "ほし" } },
  { a: { kanji: "肉", reading: "にく" }, b: { kanji: "魚", reading: "さかな" } },
  { a: { kanji: "雨", reading: "あめ" }, b: { kanji: "風", reading: "かぜ" } },
  { a: { kanji: "遠い", reading: "とおい" }, b: { kanji: "近い", reading: "ちかい" } },
  { a: { kanji: "広い", reading: "ひろい" }, b: { kanji: "せまい", reading: "せまい" } },
  { a: { kanji: "動く", reading: "うごく" }, b: { kanji: "止まる", reading: "とまる" } },
  { a: { kanji: "教える", reading: "おしえる" }, b: { kanji: "習う", reading: "ならう" } },
  { a: { kanji: "大きい", reading: "おおきい" }, b: { kanji: "小さい", reading: "ちいさい" } },
  { a: { kanji: "長い", reading: "ながい" }, b: { kanji: "短い", reading: "みじかい" } },
  { a: { kanji: "重い", reading: "おもい" }, b: { kanji: "軽い", reading: "かるい" } },
  { a: { kanji: "明るい", reading: "あかるい" }, b: { kanji: "暗い", reading: "くらい" } },
  { a: { kanji: "強い", reading: "つよい" }, b: { kanji: "弱い", reading: "よわい" } },
  { a: { kanji: "上", reading: "うえ" }, b: { kanji: "下", reading: "した" } },
  { a: { kanji: "前", reading: "まえ" }, b: { kanji: "後ろ", reading: "うしろ" } },
  { a: { kanji: "兄", reading: "あに" }, b: { kanji: "妹", reading: "いもうと" } },
  { a: { kanji: "父", reading: "ちち" }, b: { kanji: "母", reading: "はは" } },
  { a: { kanji: "買う", reading: "かう" }, b: { kanji: "売る", reading: "うる" } },
  { a: { kanji: "始まる", reading: "はじまる" }, b: { kanji: "終わる", reading: "おわる" } },
];
